language: python
python: 
        - "3.3"
        - "3.4"
        - "nightly"
install: 
        - pip install -r requirements.txt
        - pip install codecov
script: nosetests tests/
after_success:
        codecov
