language: python
python: 
        - "3.3"
        - "3.4"
        - "nightly"
install: 
        - pip install -r requirements.txt
        - pip install codecov
script: nosetests --rednose --with-cov --cov-config=.coveragerc
after_success:
        - rm -rf tests/coverages
        - codecov
