language: python
python: 
        - "3.3"
        - "3.4"
        - "nightly"
install: "pip install -r requirements.txt"
script: nosetests tests/
before_install:
        pip install codecov
after_success:
        codecov
